# -*- coding: utf-8 -*-
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
import os
import subprocess
from recommonmark.parser import CommonMarkParser
# import sys
# sys.path.insert(0, os.path.abspath('.'))


# -- General configuration ------------------------------------------------

# RTD
on_rtd = os.environ.get('READTHEDOCS', None) == 'True'

show_authors = True

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = ['sphinx.ext.mathjax',
              'matplotlib.sphinxext.plot_directive']

if not on_rtd:
    extensions.append('sphinx.ext.githubpages')

if not on_rtd:
    import sphinx_rtd_theme
    html_theme = "sphinx_rtd_theme"
    html_theme_path = [sphinx_rtd_theme.get_html_theme_path()]

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
source_parsers = {
    '.md': CommonMarkParser,
}

source_suffix = ['.rst', '.md']

# The master toctree document.
master_doc = 'index'

# General information about the project.
project = u'SM2021-COMPF2-AccBeam'
copyright = u'Under CC-BY 4.0, Snowmass 2021 COMPF2 Accelerator & Beam Physics Modeling interest group'
author = u'Snowmass 2021 COMPF2 Accelerator & Beam Physics Modeling interest group'

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The short X.Y version.
#version = u'2020.07'
# The full version, including alpha/beta/rc tags.
#release = u'2020.07'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = None

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This patterns also effect to html_static_path and html_extra_path
exclude_patterns = []

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'default'

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = False


# -- Options for HTML output ----------------------------------------------

#html_logo = 'logo.png'

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
# html_theme = 'alabaster'

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#
# html_theme_options = {}

html_context = {
  # 'Edit on Github' link instead of 'View page source'
  'display_github': True,
  'github_user': 'snowmass-compf2-accelerators',
  'github_repo': 'snowmass-compf2-accelerators.github.io',
  'github_version': 'latest',
  "conf_py_path": '/docs/source/',
  "source_suffix": source_suffix,
}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
#html_static_path = ['_static']


# -- Options for HTMLHelp output ------------------------------------------

# Output file base name for HTML help builder.
#htmlhelp_basename = 'SM2021-COMPF2-AccBeam'


# -- Options for LaTeX output ---------------------------------------------

#latex_logo = 'logo.png'

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    #
    # 'papersize': 'letterpaper',
    'papersize': 'a4paper',

    # The font size ('10pt', '11pt' or '12pt').
    #
    # 'pointsize': '10pt',

    # Additional stuff for the LaTeX preamble.
    #
    # 'preamble': '',
    'preamble': r'\setcounter{tocdepth}{2}',

    # Latex figure (float) alignment
    #
    # 'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (master_doc, 'SM2021_COMPF2_AccBeam.tex',
     u'Accelerator \& Beam Physics Modeling in the Computational Frontier (CompF2: Theoretical Calculations and Simulation) in Snowmass 2021',
     u'Accelerator \& Beam Physics Modeling interest group', 'manual'),
]


# -- Options for manual page output ---------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    (master_doc, 'Accelerator & Beam Physics Modeling',
     u'Homepage of the Accelerator & Beam Physics Modeling interest group (Snowmass 2021)',
     [author], 1)
]


# -- Options for Texinfo output -------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (master_doc, 'Accelerator & Beam Physics Modeling',
     u'Homepage of the Accelerator & Beam Physics Modeling interest group (Snowmass 2021)',
     author, 'Snowmass 2021 COMPF2 Accelerator & Beam Physics Modeling interest group',
             'Homepage of the Accelerator & Beam Physics Modeling interest group (Snowmass 2021)',
     """
     This is the homepage of the Accelerator & beam physics modeling interest
     group in the topical group Theoretical Calculations and Simulation 
     (CompF2) of the APS DPF Snowmass21 process.
     """),
]
